export const GET_USER = "GET_USER"
export const GET_USERS = "GET_USERS"
export const GET_FRIENDS = "GET_FRIENDS"
export const REGISTER_USER = "REGISTER_USER"
export const LOGIN_USER = "LOGIN_USER"
export const CREATE_USER = "CREATE_USER"
export const SET_LOADING = "SET_LOADING"
