export const MESSAGE_ERROR_TYPE = {
  MESSAGE_OUT_OF_LENGTH: "MESSAGE_OUT_OF_LENGTH",
  UN_AUTHENTICATED: "UN_AUTHENTICATED",
  INVALID_MESSAGE: "INVALID_MESSAGE",
};

export const MESSAGE_TYPE = {
  WENT_ONLINE: "WENT_ONLINE",
  WENT_OFFLINE: "WENT_OFFLINE",
  IS_TYPING: "IS_TYPING",
  NOT_TYPING: "NOT_TYPING",
  MESSAGE_COUNTER: "MESSAGE_COUNTER",
  OVERALL_MESSAGE_COUNTER: "OVERALL_MESSAGE_COUNTER",
  TEXT_MESSAGE: "TEXT_MESSAGE",
  MESSAGE_READED: "MESSAGE_READED",
  MESSAGE_DELIVERD: "MESSAGE_DELIVERD",
  ALL_MESSAGE_READ: "ALL_MESSAGE_READ",
  ERROR_OCCURED: "ERROR_OCCURED",
  MESSAGE_NOTIFICATION: "MESSAGE_NOTIFICATION",
};

export const NOTIFICATION_TYPE = {
  NEW_MESSAGE: "NEW_MESSAGE",
  READED_MESSAGE: "READED_MESSAGE",
  DELIVERD_MESSAGE: "DELIVERD_MESSAGE",
  PERSON_IS_TYPING: "PERSON_IS_TYPING",
  PERSON_NOT_TYPING: "PERSON_NOT_TYPING",
};
